- .gitignore
- nest-cli.json
- package-lock.json
- src/domain/entities/user/user.entity.ts
- src/domain/interface/users.repository.ts
- src/domain/services/auth/auth.service.ts
- src/domain/types/user.types.ts
- src/infrastructure/auth/context/oauth-context.ts
- src/infrastructure/auth/strategies/google-strategy.ts
- src/infrastructure/auth/strategies/oauth-strategy.ts
- src/infrastructure/repositories/users-prisma.repository.ts
- src/modules/auth/auth.module.ts
- src/modules/user/users.module.ts
- src/presentation/controllers/auth/auth.controller.ts
- src/presentation/controllers/user/users.controller.ts
- src/presentation/dto/auth/register.request.ts
- src/presentation/dto/user/upload-image.response.ts
- tsconfig.json
feature : tsconfig.json, nest-cli.json 수정
chore : 기존 상대 경로 절대 경로로 변경
> [#26] import 상대 -> 절대 경로로 변경

- prisma/migrations/20250103132223_merge_friend_and_friend_request/migration.sql
- prisma/migrations/20250103132302_fix_updated_at_naming/migration.sql
- prisma/migrations/20250103132759_merge_gathering_invitation_and_participation/migration.sql
- prisma/migrations/20250103134040_add_updated_at_column/migration.sql
- prisma/migrations/20250103134635_add_gathering_id_column_to_feed/migration.sql
- prisma/migrations/20250103135418_naming_mapping/migration.sql
- prisma/schema.prisma
- src/domain/entities/user/user.entity.ts
- 친구, 친구 요청 테이블 병합 및 status 컬럼 추가.
- 모임 초대, 모임 참여 테이블 병합 및 status 컬럼 추가
- updated_at 컬럼 필요 테이블에 추가.
- 피드 테이블에 누락된 모임 번호 fk 추가.
> 테이블 병합 및 컬럼 추가

- package-lock.json
- package.json
- prisma/generated/types.ts
- prisma/migrations/20250103151350_change_column_avatar_url_to_profile_image_url/migration.sql
- prisma/schema.prisma
- src/domain/interface/users.repository.ts
- src/domain/services/user/users.service.ts
- src/domain/types/user.types.ts
- src/infrastructure/prisma/prisma.service.ts
- src/infrastructure/repositories/users-prisma.repository.ts
- src/infrastructure/types/user.types.ts
- src/modules/auth/auth.module.ts
- src/modules/user/users.module.ts
- src/presentation/controllers/user/users.controller.ts
- src/presentation/dto/user/search-user.request.ts
- src/presentation/dto/user/search-user.response.ts
- src/presentation/dto/user/user-pagination.request.ts
- src/shared/types/index.ts
- test/e2e/jest-e2e.json
- test/e2e/users.e2e-spec.ts
- test/helpers/generators.ts
- test/helpers/login.ts
- test/helpers/types.ts
- test/unit/jest.json
- 쿼리빌더 kysely 추가. fece8e7c70751a41ec76a38277452952570d2828
- 회원 검색 기능 구현.
- 회원 검색 정상 동작 e2e 테스트 작성.
- 테스트에 사용할 로그인 함수, 회원 엔티티 생성 함수 구현.
- -D dotenv-cli
- 개발 시에는 .env 파일을 사용하고, 테스트 시에는 .env.test 파일을 주입하여 사용하도록 했습니다.
- 이 부분은 혹시 불편하시면 얼마든지 제거 가능해요 말씀부탁드려요.
> 회원 검색 기능 구현

- src/common/decorators/swagger/index.ts
- src/domain/interface/group/groups.repository.ts
- src/domain/services/group/groups.service.ts
- src/domain/shared/get-cursor.ts
- src/domain/types/group.types.ts
- src/infrastructure/repositories/group/groups-prisma.repository.ts
- src/modules/group/groups.module.ts
- src/presentation/controllers/auth/auth.controller.ts
- src/presentation/controllers/group/groups.controller.ts
- src/presentation/converters/group/group.converters.ts
- src/presentation/dto/friend/request/search-friend.request.ts
- src/presentation/dto/friend/response/data.types.ts
- src/presentation/dto/friend/response/friend-list.response.ts
- src/presentation/dto/friend/response/friend-request-list.response.ts
- src/presentation/dto/group/index.ts
- src/presentation/dto/group/response/group-list.response.ts
- src/presentation/dto/package.json
- src/presentation/dto/shared/index.ts
- src/presentation/dto/tsconfig.json
- src/presentation/dto/user/request/search-user.request.ts
- src/presentation/dto/user/response/search-user.response.ts
- src/shared/types/index.ts
- test/e2e/groups.e2e-spec.ts
- test/helpers/generators.ts
- 그룹 목록 조회 기능 구현.
- 그룹 목록 조회 정상 동작 e2e 테스트 작성.
> 그룹 목록 조회 기능 구현

- package.json
- src/configs/winston/winston-options.ts
- src/main.ts
- 기본 로거 winston으로 설정.
- 로그 파일 저장.
- winston
- nest-winston
> 로거 winston 추가

- src/domain/services/group/group-create.service.ts
- src/presentation/controllers/group/groups.controller.ts
- src/presentation/dto/group/index.ts
- src/presentation/dto/group/request/add-group-member.request.ts
- src/presentation/dto/group/request/create-group.request.ts
- test/e2e/groups.e2e-spec.ts
> 그룹원 추가 기능 구현

- prisma/generated/types.ts
- prisma/migrations/20250110135424_remove_deleted_at_to_group_participation/migration.sql
- prisma/migrations/20250110144928_add_on_delete_cascade_to_group_participation/migration.sql
- prisma/schema.prisma
- src/domain/error/messages/index.ts
- src/domain/interface/group/group-participations.repository.ts
- src/domain/interface/group/groups.repository.ts
- src/domain/services/group/group-create.service.ts
- src/infrastructure/repositories/group/group-participations-prisma.repository.ts
- src/infrastructure/repositories/group/groups-prisma.repository.ts
- src/presentation/controllers/group/groups.controller.ts
- test/e2e/groups.e2e-spec.ts
- #46 
- 그룹 나가기 기능 구현.
- 정상동작 e2e 작성.
- 그룹장이 나가려는 예외 케이스 e2e 작성.
- 그룹 삭제 기능 구현.
- 정상동작 e2e 작성.
- 그룹장이 아닌 회원이 삭제하려는 예외 케이스 e2e 작성
> 그룹 나가기 삭제 기능 구현

- prisma/generated/types.ts
- prisma/migrations/20250111035356_set_nullable_profile_image_url_to_user/migration.sql
- prisma/schema.prisma
- #30 
- user 테이블의 profileImageUrl nullable로 변경.
- 프로필 이미지 업로드 api에 인가를 위함.
> profileImageUrl 컬럼 nullable로 변경

- src/domain/entities/user/user.entity.ts
- src/domain/interface/gathering/gathering-participations.repository.ts
- src/domain/services/gathering/gatherings-write.service.ts
- src/domain/types/user.types.ts
- src/infrastructure/repositories/gathering/gathering-participations-prisma.repository.ts
- src/presentation/controllers/gathering/gatherings.controller.ts
- src/shared/types/index.ts
- test/e2e/gathering.e2e-spec.ts
- test/helpers/generators.ts
- #10 
- 모임 초대 수락 기능 구현.
- 정상 동작 e2e.
- 모임 초대 거절 기능 구현.
- 정상 동작 e2e
> 모임 초대 수락 거절 기능 구현

- package.json
- src/common/decorators/swagger/index.ts
- src/domain/interface/gathering/gathering-participations.repository.ts
- src/domain/services/gathering/gathering-invitations-read.service.ts
- src/domain/shared/get-cursor.ts
- src/domain/types/gathering.types.ts
- src/infrastructure/repositories/gathering/gathering-participations-prisma.repository.ts
- src/modules/gathering/gatherings.module.ts
- src/presentation/controllers/gathering/gatherings.controller.ts
- src/presentation/controllers/group/groups.controller.ts
- src/presentation/converters/gathering/gathering-invitation.converters.ts
- src/presentation/dto/gathering/request/create-gathering.request.ts
- src/presentation/dto/gathering/request/gathering-invitation-list.request.ts
- src/presentation/dto/gathering/response/gathering-invitation-list.response.ts
- src/presentation/dto/group/response/group-list.response.ts
- src/presentation/dto/shared/index.ts
- src/presentation/dto/user/request/user-pagination.request.ts
- src/presentation/dto/user/response/data.types.ts
- src/shared/types/index.ts
- test/e2e/gathering.e2e-spec.ts
- test/helpers/generators.ts
- #53 
- 받은 모임 초대 목록 조회 기능 구현.
- 정상 동작 e2e 작성.
- 보낸 모임 초대 목록 조회 기능 구현.
- 정상 동작 e2e 작성.
- swagger 전체적으로 예제 및 설명 보강.
> 모임 초대 조회 기능 구현

- package.json
- prisma/seed.ts
> db seed 파일 추가

- prisma/generated/types.ts
- prisma/migrations/20250117120320_remove_updated_at_to_feed_comment/migration.sql
- prisma/schema.prisma
- src/app.module.ts
- src/domain/entities/feed-comment/feed-comment.entity.ts
- src/domain/error/messages/index.ts
- src/domain/interface/feed-comment/feed-comments.repository.ts
- src/domain/services/feed-comment/feed-comments.service.ts
- src/domain/types/feed-comment.types.ts
- src/infrastructure/repositories/feed-comment/feed-comment-prisma.repository.ts
- src/infrastructure/repositories/feed/feeds-prisma.repository.ts
- src/modules/feed-comment/feed-comments.module.ts
- src/presentation/controllers/feed-comment/feed-comment.controller.ts
- src/presentation/converters/feed-comment/feed-comment.converters.ts
- src/presentation/dto/comment/request/create-feed-comment.request.ts
- src/presentation/dto/comment/response/feed-comment-list.response.ts
- src/presentation/dto/user/response/data.types.ts
- test/e2e/feed-comment.e2e-spec.ts
- test/e2e/feed2.e2e-spec.ts
- test/e2e/gathering.e2e-spec.ts
- test/helpers/generators.ts
- #19
- 댓글 작성 기능.
- 댓글 목록 조회 기능.
- 댓글 삭제 기능.
- 댓글 관련 모든 기능 정상 동작 e2e 작성
- feed_comment는 업데이트가 없기 때문에 updated_at 컬럼 제거
> 피드 댓글 기능 구현

- src/domain/interface/group/groups.repository.ts
- src/domain/services/group/group-create.service.ts
- src/infrastructure/repositories/group/groups-prisma.repository.ts
- src/presentation/controllers/group/groups.controller.ts
- src/presentation/dto/group/index.ts
- src/presentation/dto/group/request/update-description.request.ts
- src/presentation/dto/package.json
- test/e2e/groups.e2e-spec.ts
- #65 
- 그룹 소개 변경 기능 구현.
- 정상 동작 e2e 작성.
> 그룹 설명 변경 기능 구현

- src/domain/interface/friend/friends.repository.ts
- src/domain/services/friend/friends.service.ts
- src/infrastructure/repositories/friend/friends.prisma.repository.ts
- src/presentation/controllers/friend/friends.controller.ts
- test/e2e/friends.e2e-spec.ts
- #76 
- 친구 삭제 기능 구현.
- 정상 동작 e2e 작성.
> 친구 삭제 기능 구현

- src/domain/interface/feed/feeds.repository.ts
- src/domain/services/feed/feeds-write.service.ts
- src/infrastructure/repositories/feed/feeds-prisma.repository.ts
- src/presentation/controllers/feed/feeds.controller.ts
- test/e2e/feed2.e2e-spec.ts
- #79 
- 피드 삭제 기능 구현.
- 조회 시 deletedAt 조건 추가.
- 정상 동작 e2e 작성.
> 피드 삭제 기능 구현

- src/common/constant.ts
- src/infrastructure/auth/context/oauth-context.ts
- src/infrastructure/auth/strategies/kakao-strategy.ts
- src/modules/auth/auth.module.ts
> 카카오 로그인 구현

- src/application/use-cases/feed-comment/feed-comment.use-case.ts
- src/application/use-cases/friend/friend-acceptance.use-case.ts
- src/application/use-cases/friend/friend-request.use-case.ts
- src/application/use-cases/gathering/gathering-invitation-acceptance.use-case.ts
- src/application/use-cases/group/group-creation.use-case.ts
- src/domain/components/friend/friends-checker.ts
- src/domain/components/notification/notification-manager.ts
- src/domain/components/notification/notifications-reader.ts
- src/domain/components/notification/notifications-writer.ts
- src/domain/components/notification/notifications.service.ts
- src/domain/services/friends/friends.service.ts
- src/infrastructure/event/event.module.ts
- src/infrastructure/repositories/gathering/gathering-participations-prisma.repository.ts
- src/modules/auth/auth.module.ts
- src/modules/feed-comment/feed-comments.module.ts
- src/modules/friend/friends.module.ts
- src/modules/gathering/gatherings.module.ts
- src/modules/group/groups.module.ts
- src/modules/notification/notifications-component.module.ts
- src/modules/notification/notifications-manager.module.ts
- src/modules/notification/notifications.module.ts
- src/modules/user/users.module.ts
- src/modules/user/usesr.component.module.ts
- test/unit/service/friends.service.unit-spec.ts
- 친구 서비스 단위 테스트 작성
- 작성 테스트는 commit message에서 확인
- 실수로 푸시 알림과 같은 조건으로 묶어놨던 알림 데이터 생성을 조건문 밖으로 이동
- 알림 component 레이어 생성.
- 알림 모듈에서, component module(컴포넌트 레이어), manager module(알림 생성 전송자) 분리
> 친구 서비스 단위 테스트 작성 및 알림 도메인 리팩토링

- prisma/migrations/20250301075113_change_id_type_to_uuid_and_remove_fk/migration.sql
- prisma/migrations/20250301155249_add_unique_index/migration.sql
- prisma/migrations/20250301161637_add_index/migration.sql
- prisma/migrations/20250301162118_create_view/migration.sql
- prisma/schema.prisma
- src/domain/services/gatherings/gatherings.service.ts
- src/infrastructure/prisma/get-kysely-uuid.ts
- src/infrastructure/repositories/feed/feeds-prisma.repository.ts
- src/infrastructure/repositories/feed/friend-feed-visibilities-prisma.repository.ts
- src/infrastructure/repositories/friend/friends.prisma.repository.ts
- src/infrastructure/repositories/gathering/gathering-participations-prisma.repository.ts
- src/infrastructure/repositories/gathering/gatherings-prisma.repository.ts
- src/infrastructure/repositories/group/groups-prisma.repository.ts
- src/infrastructure/repositories/users-prisma.repository.ts
- src/presentation/dto/package.json
- test/e2e/feed2.e2e-spec.ts
- test/e2e/friends.e2e-spec.ts
- test/e2e/gathering.e2e-spec.ts
- test/e2e/groups.e2e-spec.ts
- 모든 테이블에서 fk 제약 조건 제거.
- 성능, 마이그레이션 이슈.
- 모든 테이블의 id 타입을 uuid로 변경, 원래 uuid였어야하는데 실수로 text로 전부 설정함.
> 모든 테이블 id 컬럼 타입 변경 및 fk 제거

- src/app.module.ts
- src/common/filters/global-exception.filter.ts
- src/configs/config-module/validation.ts
- src/configs/sentry/instrument.ts
- src/main.ts
- sentry 에러 알림 기능 추가
- 500번대 에러만 sentry에 이슈로 생성되고, discord 알림 전송.
> sentry 에러 알림 추가

- src/domain/components/friend/friends-reader.ts
- src/domain/interface/friend/friends.repository.ts
- src/infrastructure/repositories/friend/friends.prisma.repository.ts
- src/presentation/controllers/friend/friends.controller.ts
- src/presentation/dto/friend/index.ts
- src/presentation/dto/friend/response/friend-request-count.response.ts
- test/e2e/friends.e2e-spec.ts
- 전체 친구 요청 수 조회 기능 구현
- 받은 + 보낸 요청
> 친구 요청 수 조회 기능 구현

- package-lock.json
- package.json
- src/configs/config-module/validation.ts
- src/configs/winston/winston-options.ts
- 프러덕션 환경에서 cloudwatch로 로그 전송 추가
> cloudwatch 추가

- src/infrastructure/event/event.module.ts
- test/e2e/friends.e2e-spec.ts
- test/unit/service/gatherings.service.unit-spec.ts
> notify 이벤트 수신 안 되던 현상 수정

- deploy.sh
- 모든 과정 logs/deploy.log에 로깅.
- 빌드 실패하면 스크립트 중단
> 배포 스크립트 명령 추가

- src/domain/components/gathering/gatherings-reader.ts
- src/domain/interface/gathering/gatherings.repository.ts
- src/infrastructure/repositories/gathering/gatherings-prisma.repository.ts
- src/presentation/controllers/gathering/gatherings.controller.ts
- src/presentation/dto/gathering/request/gathering-list.request.ts
- test/e2e/gathering.e2e-spec.ts
- 참여 모임 완료 여부 관계 없이 전체 조회하는 api 추가
- **```/gatherings/all```**
> 참여 모임 전체 조회 기능 구현

- src/infrastructure/repositories/feed/feeds-prisma.repository.ts
- test/e2e/feed2.e2e-spec.ts
- test/unit/reader/feeds.reader.unit-spec.ts
- 전체 피드 조회에 자신이 작성한 피드도 노출되도록 기획 변경됨에 따라 기능 수정
> 피드 전체 조회에 자신이 작성하 피드도 노출되도록 변경

- src/infrastructure/repositories/feed/feeds-prisma.repository.ts
- 피드 전체 조회 (feedsPrismaRepo - findAllByUserId) 서브쿼리에서 중복 피드 조회 가능성 있는 쿼리 수정
- groupBy가 중복 제거 역할을 못하는 상황이 존재했었음. (f.id, f.createdAt) 였으니 당연함.
- 중복 방지 및 너무 많은 튜플 수 증가를 막기 위해 gathering만 left join하고, 나머지 조건은 in 절로 대체.
-> 성능 비교 테스트도 해보기.
> 피드 전체 조회 서브쿼리에서 중복 피드 조회 가능성 있는 쿼리 수정

- prisma/generated/types.ts
- prisma/migrations/20250321180800_create_blocked_comment_table/migration.sql
- prisma/schema.prisma
- src/common/filters/http-exception.filter.ts
- src/common/interceptors/logging.interceptor.ts
- src/domain/components/feed-comment/feed-comment-reader.ts
- src/domain/components/report/feed-comment-reports-write.service.ts
- src/domain/entities/feed-comment/blocked-feed-comment.entity.ts
- src/domain/interface/feed-comment/blocked-feed-comment.repository.ts
- src/domain/interface/feed-comment/feed-comments.repository.ts
- src/domain/services/feed-comments/feed-comments.service.ts
- src/infrastructure/repositories/feed-comment/blocked-feed-comment-prisma.repository.ts
- src/infrastructure/repositories/feed-comment/feed-comment-prisma.repository.ts
- src/modules/feed-comment/feed-comments-component.module.ts
- src/modules/feed-comment/feed-comments.module.ts
- src/modules/report/reports.module.ts
- src/presentation/controllers/feed-comment/feed-comment.controller.ts
- test/e2e/report.e2e-spec.ts
- test/helpers/generators.ts
- test/unit/reader/feed-comments.reader.unit-spec.ts
- blocked_feed_comment 테이블 생성.
- 댓글 신고 시 숨김 처리.
- production 환경에서 forward ip 로깅하도록 변경.
- 500번만 error레벨 400번대는 warn 레벨로 변경.
> 댓글 신고 시 숨김 처리 구현

- prisma/migrations/20250322160509_add_pk_to_blocked_table/migration.sql
- prisma/schema.prisma
- src/domain/components/feed-comment/feed-comment-reader.ts
- src/domain/components/feed-comment/feed-comments-writer.ts
- src/domain/error/exceptions/not-found.exception.ts
- src/domain/services/feed-comments/feed-comments.service.ts
- src/infrastructure/repositories/group/groups-prisma.repository.ts
- src/modules/feed-comment/feed-comments-component.module.ts
- src/modules/feed-comment/feed-comments.module.ts
- test/unit/reader/feed-comments.reader.unit-spec.ts
- test/unit/reader/groups-reader.unit-spec.ts
- blocked 테이블 id 컬럼 조합으로 pk 설정.
- REPORTED 상태인 그룹이 조회되던 현상 수정.
- 그룹 목록 조회 테스트 작성
- 정상 동작
- REPORTED 상태 조회 x
> blocked 테이블 pk 설정 및 REPORTED 상태 그룹 조회 되던 현상 수정

- src/domain/components/token/refresh-token-writer.ts
- src/domain/interface/token/refresh-token.repository.ts
- src/domain/services/user/users.service.ts
- src/infrastructure/repositories/token/refresh-token-prisma.repository.ts
- src/modules/user/users.module.ts
- src/presentation/controllers/user/users.controller.ts
- test/unit/service/users.service.unit-spec.ts
- 회원 탈퇴 시 저장된 모든 refresh token 삭제
> 회원 탈퇴 시 모든 토큰 삭제

- src/presentation/dto/auth/request/register.request.ts
> 가입 요청 검증 수정

- prisma/generated/types.ts
- prisma/migrations/20250409075837_add_metion_to_feed_comment/migration.sql
- prisma/migrations/20250409080058_change_col_name_mention_user_id/migration.sql
- prisma/migrations/20250409092618_add_relation_to_comment_mention/migration.sql
- prisma/schema.prisma
- src/common/constant.ts
- src/domain/components/notification/notification-manager.ts
- src/domain/entities/feed-comment/feed-comment.entity.ts
- src/domain/error/exceptions/unprocessable.exception.ts
- src/domain/error/messages/index.ts
- src/domain/services/feed-comments/feed-comments.service.ts
- src/domain/types/feed-comment.types.ts
- src/infrastructure/repositories/feed-comment/feed-comment-prisma.repository.ts
- src/modules/notification/notifications-manager.module.ts
- src/modules/notification/notifications.module.ts
- src/presentation/dto/comment/request/create-feed-comment.request.ts
- src/presentation/dto/comment/response/feed-comment-list.response.ts
- src/presentation/dto/feed/index.ts
- src/presentation/dto/notification/response/notification-list.response.ts
- src/presentation/dto/package.json
- test/e2e/feed-comment.e2e-spec.ts
- test/helpers/generators.ts
- test/unit/reader/feed-comments.reader.unit-spec.ts
- 댓글 맨션 기능.
- 맨션 알림도 추가
- feed-comment 테이블에 mentionedUserId 컬럼 옵셔널로 추가.
- user 테이블과 prisma 내에서만 n:1 연관 관계 가짐.
- 알림 타입 enum에 FEED_COMMENT_MENTIONED 추가.
> 댓글 맨션 기능 추가
